TEAM_CHOICES = [
                ('Arsenal', 'Arsenal'), 
                ('Aston Villa', 'Aston Villa'), 
                ('Birmingham', 'Birmingham'), 
                ('Blackburn', 'Blackburn'), 
                ('Blackpool', 'Blackpool'), 
                ('Bolton', 'Bolton'), 
                ('Bournemouth', 'Bournemouth'), 
                ('Brentford', 'Brentford'), 
                ('Brighton', 'Brighton'), 
                ('Burnley', 'Burnley'), 
                ('Cardiff', 'Cardiff'), 
                ('Chelsea', 'Chelsea'), 
                ('Crystal Palace', 'Crystal Palace'), 
                ('Derby', 'Derby'), 
                ('Everton', 'Everton'), 
                ('Fulham', 'Fulham'), 
                ('Huddersfield', 'Huddersfield'), 
                ('Hull', 'Hull'), ('Leeds', 'Leeds'), 
                ('Leicester', 'Leicester'), 
                ('Liverpool', 'Liverpool'), 
                ('Man City', 'Man City'), 
                ('Man United', 'Man United'), 
                ('Middlesbrough', 'Middlesbrough'), 
                ('Newcastle', 'Newcastle'), 
                ('Norwich', 'Norwich'), 
                ('Portsmouth', 'Portsmouth'), 
                ('QPR', 'QPR'), 
                ('Reading', 'Reading'), 
                ('Sheffield United', 'Sheffield United'), 
                ('Southampton', 'Southampton'), 
                ('Stoke', 'Stoke'), 
                ('Sunderland', 'Sunderland'), 
                ('Swansea', 'Swansea'), 
                ('Tottenham', 'Tottenham'), 
                ('Watford', 'Watford'), 
                ('West Brom', 'West Brom'), 
                ('West Ham', 'West Ham'), 
                ('Wigan', 'Wigan'), 
                ('Wolves', 'Wolves')
                ]